"""Data import module: imports from clean JSON files (generated by convert_excel_to_json.py)
into PostgreSQL using UPSERT for idempotent data loading.

Flow: Excel → [convert_excel_to_json.py] → JSON → [import_from_json] → PostgreSQL

Also includes legacy import_from_excel() for backward compatibility.
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import pandas as pd
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession


async def import_from_json(
    db: AsyncSession,
    companies_path: str = "data/companies.json",
    works_path: str = "data/works.json",
) -> dict:
    """Import data from clean JSON files into PostgreSQL.

    This is the RECOMMENDED import method. The JSON files are produced by
    scripts/convert_excel_to_json.py which handles all Excel edge cases
    (merged cells, quantity parsing, rating classification, type detection).

    Uses UPSERT for idempotency — safe to run multiple times.

    Args:
        db: Async database session
        companies_path: Path to companies.json
        works_path: Path to works.json

    Returns:
        dict with import statistics
    """
    stats = {"companies_added": 0, "works_added": 0, "works_skipped": 0, "errors": []}

    # ── Load JSON files ──
    for path, label in [(companies_path, "companies"), (works_path, "works")]:
        if not Path(path).exists():
            raise FileNotFoundError(f"JSON file not found: {path}\n"
                                    f"  Run: python scripts/convert_excel_to_json.py first")

    with open(companies_path, "r", encoding="utf-8") as f:
        companies_data = json.load(f)
    with open(works_path, "r", encoding="utf-8") as f:
        works_data = json.load(f)

    companies_list = companies_data.get("companies", [])
    works_list = works_data.get("works", [])

    print(f"  [-] 导入 {len(companies_list)} 家公司, {len(works_list)} 部作品")

    # ── 1. Import companies ──
    company_id_map = {}  # name → id

    for comp in companies_list:
        try:
            name = comp["name"].strip()
            if not name:
                continue

            now = datetime.now(timezone.utc)
            result = await db.execute(
                text(
                    """INSERT INTO companies (name, type, created_at, updated_at)
                    VALUES (:name, :type, :now, :now)
                    ON CONFLICT (name) DO UPDATE SET
                        type = EXCLUDED.type,
                        updated_at = :now
                    RETURNING id"""
                ),
                {"name": name, "type": comp.get("type", "3D"), "now": now},
            )
            cid = result.scalar_one()
            company_id_map[name] = cid
            stats["companies_added"] += 1
        except Exception as e:
            stats["errors"].append(f"Company '{comp.get('name', '?')}': {e}")

    print(f"  [OK] 公司导入完成: {stats['companies_added']} 家")

    # ── 2. Import works ──
    batch_size = 100
    batch = []

    for work in works_list:
        try:
            comp_name = work.get("company_name", "").strip()
            work_name = work.get("name", "").strip()

            if not comp_name or not work_name:
                continue

            company_id = company_id_map.get(comp_name)
            if not company_id:
                stats["errors"].append(f"Work '{work_name}': company '{comp_name}' not found")
                continue

            batch.append({
                "company_id": company_id,
                "name": work_name,
                "year": work.get("year"),
                "rating_raw": work.get("rating_raw"),
                "rating_label": work.get("rating_label"),
                "rating_score": work.get("rating_score"),
                "now": datetime.now(timezone.utc),
            })

            # Flush batch
            if len(batch) >= batch_size:
                await _upsert_works_batch(db, batch, stats)
                batch = []

        except Exception as e:
            stats["errors"].append(f"Work '{work.get('name', '?')}': {e}")

    # Final batch
    if batch:
        await _upsert_works_batch(db, batch, stats)

    await db.commit()
    print(f"  [OK] 作品导入完成: {stats['works_added']} 新增, {stats['works_skipped']} 跳过")

    return stats


async def _upsert_works_batch(db: AsyncSession, batch: list[dict], stats: dict):
    """Upsert a batch of works using raw SQL for performance."""
    for w in batch:
        result = await db.execute(
            text(
                """INSERT INTO works (company_id, name, year, rating_raw, rating_label, rating_score, quantity, created_at, updated_at)
                VALUES (:company_id, :name, :year, :rating_raw, :rating_label, :rating_score, 1, :now, :now)
                ON CONFLICT (company_id, name) DO UPDATE SET
                    year = EXCLUDED.year,
                    rating_raw = EXCLUDED.rating_raw,
                    rating_label = EXCLUDED.rating_label,
                    rating_score = EXCLUDED.rating_score,
                    updated_at = :now
                RETURNING id"""
            ),
            w,
        )
        row = result.fetchone()
        if row:
            stats["works_added"] += 1
        else:
            stats["works_skipped"] += 1


# ============================================================
# Legacy: direct Excel import (备用方案)
# ============================================================

RATING_PATTERNS = {
    "年度推荐": re.compile(r"年度推荐|强推荐|强烈推荐|年度.*推荐", re.IGNORECASE),
    "佳作": re.compile(r"佳作|推荐(?!年度)|力荐", re.IGNORECASE),
    "还行": re.compile(r"还行|不错|可以|一般", re.IGNORECASE),
    "能看": re.compile(r"能看|凑合|勉强", re.IGNORECASE),
    "不明": re.compile(r"不明|未知|暂无|待定", re.IGNORECASE),
    "拉了": re.compile(r"拉了|拉胯|不行|差", re.IGNORECASE),
    "史": re.compile(r"史|烂|垃圾|极差", re.IGNORECASE),
}

# V2 评分体系（与 convert_excel_to_json.py 保持一致）
RATING_SCORE_MAP = {
    "年度推荐": 4.0, "佳作": 2.0, "还行": 0.5, "能看": -0.5,
    "不明": 0.0, "拉了": -1.0, "史": -2.0,
}

TYPE_PATTERNS = {
    "2D": re.compile(r"2D|二维|2d", re.IGNORECASE),
    "3D": re.compile(r"3D|三维|3d", re.IGNORECASE),
    "三渲二": re.compile(r"三渲二|三转二|3D.*2D|2D.*3D|卡通渲染", re.IGNORECASE),
}


async def import_from_excel(
    db: AsyncSession,
    filepath: str,
    *,
    sheet_name: int = 0,
) -> dict:
    """LEGACY: Direct Excel import with basic cleaning.

    Prefer using convert_excel_to_json.py + import_from_json() for production use.
    This method is kept as a fallback for simple Excel files without merged cells.
    """
    path = Path(filepath)
    if not path.exists():
        raise FileNotFoundError(f"Excel file not found: {filepath}")

    xls = pd.ExcelFile(filepath)
    sheet = sheet_name if isinstance(sheet_name, str) else xls.sheet_names[sheet_name]
    df = pd.read_excel(filepath, sheet_name=sheet)

    # Auto-detect columns
    col_map = _detect_columns(df.columns.tolist())
    df = df.rename(columns=col_map)

    # ffill merged cells
    for col in ["动画公司", "制作"]:
        if col in df.columns:
            df[col] = df[col].ffill()

    stats = {"companies_added": 0, "works_added": 0, "errors": []}
    company_id_map = {}

    for _, row in df.iterrows():
        try:
            company_name = str(row.get("动画公司", "")).strip()
            if not company_name or company_name == "nan":
                continue

            # UPSERT company (cache in map)
            if company_name not in company_id_map:
                raw_type = str(row.get("制作", ""))
                ctype = "3D"
                for ct, pat in TYPE_PATTERNS.items():
                    if pat.search(raw_type):
                        ctype = ct
                        break

                result = await db.execute(
                    text(
                        """INSERT INTO companies (name, type) VALUES (:name, :type)
                        ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, updated_at = now()
                        RETURNING id"""
                    ),
                    {"name": company_name, "type": ctype},
                )
                company_id_map[company_name] = result.scalar_one()
                stats["companies_added"] += 1

            cid = company_id_map[company_name]

            # Work
            work_name = str(row.get("动画名", "")).strip()
            if not work_name or work_name == "nan":
                continue

            year_val = row.get("年份")
            try:
                year = int(year_val) if not pd.isna(year_val) else None
            except (ValueError, TypeError):
                year = None

            raw_rating = str(row.get("评级", ""))
            label, score = None, None
            for lbl, pat in RATING_PATTERNS.items():
                if pat.search(raw_rating):
                    label, score = lbl, RATING_SCORE_MAP[lbl]
                    break

            result = await db.execute(
                text(
                    """INSERT INTO works (company_id, name, year, rating_raw, rating_label, rating_score, quantity)
                    VALUES (:company_id, :name, :year, :rating_raw, :rating_label, :rating_score, 1)
                    ON CONFLICT (company_id, name) DO UPDATE SET
                        year = EXCLUDED.year, rating_raw = EXCLUDED.rating_raw,
                        rating_label = EXCLUDED.rating_label, rating_score = EXCLUDED.rating_score,
                        updated_at = now()
                    RETURNING id"""
                ),
                {
                    "company_id": cid, "name": work_name, "year": year,
                    "rating_raw": raw_rating[:50] if raw_rating else None,
                    "rating_label": label, "rating_score": score,
                },
            )
            if result.fetchone():
                stats["works_added"] += 1

        except Exception as e:
            stats["errors"].append(f"Row: {e}")

    await db.commit()
    return stats


def _detect_columns(columns: list) -> dict:
    """Auto-detect column names from Excel headers."""
    mapping = {}
    patterns = {
        "动画公司": [r"动画公司", r"公司$", r"公司名称"],
        "制作": [r"制作", r"类型$", r"^类型"],
        "动画名": [r"动画名", r"作品名", r"作品名称", r"动画作品"],
        "年份": [r"年份", r"播出年份", r"首播年份"],
        "评级": [r"评级", r"评价", r"作品评价"],
        "数量": [r"数量", r"作品数量"],
    }
    for col in columns:
        for target, pats in patterns.items():
            if any(re.search(p, str(col)) for p in pats):
                mapping[col] = target
                break
    return mapping
